# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Dev
    jobs:
     - job: BuildApplication
       pool:
         vmImage: ubuntu-latest
       steps:
         - task: NodeTool@0
           displayName: 'Use Node 14'
           inputs:
             versionSpec: '14.x'
         - task: Npm@1
           displayName: 'Install Application Dependencies'
           inputs:
             command: 'install'
             workingDir: '.'
            #  customRegistry: 'useFeed'
            #  customFeed: '4f92a9d6-ce6d-44de-a4d1-dd4c2f11f052'
        #  - task: Npm@1
        #    displayName: 'Run "test" script'
        #    inputs:
        #      command: 'custom'
        #      workingDir: 'source'
        #      customCommand: 'test'
        #      customRegistry: 'useFeed'
        #      customFeed: '4f92a9d6-ce6d-44de-a4d1-dd4c2f11f052'
         - task: ArchiveFiles@2
           displayName: 'Archive code'
           inputs:
              rootFolderOrFile: '.'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
         - task: PublishBuildArtifacts@1
           displayName: "Publish"
           inputs:
             PathtoPublish: '$(Build.ArtifactStagingDirectory)'
             ArtifactName: 'drop'
             publishLocation: 'Container'